[build]
  command = ""
  publish = "public/dist"

[[headers]]
  for = "*.wasm"
  [headers.values]
  Content-Type = "application/wasm"

[[headers]]
  for = "assets/dice-box/**"
  [headers.values]
  Content-Type = "application/wasm"
  Access-Control-Allow-Origin = "*"
